//
//  helloworldPresenter.swift
//  TestCleanSwift
//
//  Created by Martin Demiddel on 31.10.18.
//  Copyright (c) 2018 Martin Bing. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol helloworldPresentationLogic
{
  func presentSomething(response: helloworld.Something.Response)
}

class helloworldPresenter: helloworldPresentationLogic
{
  weak var viewController: helloworldDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: helloworld.Something.Response)
  {
    let viewModel = helloworld.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
