//
//  helloworldModels.swift
//  TestCleanSwift
//
//  Created by Martin Demiddel on 31.10.18.
//  Copyright (c) 2018 Martin Bing. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum helloworld
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
