//
//  helloworldRouter.swift
//  TestCleanSwift
//
//  Created by Martin Demiddel on 31.10.18.
//  Copyright (c) 2018 Martin Bing. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol helloworldRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol helloworldDataPassing
{
  var dataStore: helloworldDataStore? { get }
}

class helloworldRouter: NSObject, helloworldRoutingLogic, helloworldDataPassing
{
  weak var viewController: helloworldViewController?
  var dataStore: helloworldDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: helloworldViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: helloworldDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
